# Generated by Django 3.0.2 on 2020-01-31 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='avatar')),
                ('total_expense', models.FloatField(default=0, verbose_name='Total Expenses')),
                ('monthly_stipend', models.FloatField(default=0, verbose_name='Monthly Expense')),
                ('active', models.BooleanField(default=True, verbose_name='Active Account')),
                ('currency', models.CharField(default='INR', max_length=5, verbose_name='Currency')),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'managed': True,
            },
        ),
    ]
