# Generated by Django 3.0.2 on 2020-01-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(default='example@upi', max_length=100, verbose_name='UPI ID'),
        ),
    ]
