# Generated by Django 3.0.2 on 2020-02-01 04:16

import accounts.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_profile_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(default='example@upi', max_length=100, validators=[accounts.validators.validate_upi_id], verbose_name='UPI ID'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Group Title')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
