# Generated by Django 3.0.2 on 2020-02-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200201_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group', to='accounts.Profile'),
        ),
    ]
