# Generated by Django 3.0.2 on 2020-01-31 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DateTime'),
            preserve_default=False,
        ),
    ]
