# Generated by Django 3.0.2 on 2020-02-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='DateTime'),
        ),
    ]
